[package]
name = "sui_multisig"
version = "0.0.1"
authors = ["https://github.com/johannafransn"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
sui_multisig =  "0x0"
sui =  "0x2"
